import {asset} from "./asset.ts";

type GraphEdge = { f: number; d: number; t?: number; p: number }
type AirportGraph = Record<string, Record<string, GraphEdge>>

/** A route between two airports in the route network. */
export interface Route {
  /** ICAO code of the origin airport. */
  origin: string
  /** ICAO code of the destination airport. */
  destination: string
  /** Number of flights per day along this route. */
  frequency: number
  /** Great-circle distance in kilometres. */
  distance: number
  /** Average flight time in minutes, if known. */
  duration?: number
}

/**
 * The set of airports and routes that make up a single game instance,
 * generated by selecting a connected subgraph of the route network.
 */
export interface GameData {
  icaoCodes: string[]
  routes: Route[]
  /** Base price per route, keyed by sorted `"ORIG-DEST"` ICAO pair. Values are in the range [1, 99]. */
  prices: Map<string, number>
}

/**
 * Builds the core game data from the route graph asset.
 *
 * Loads the route graph JSON, flattens it into a list of routes, and reads the
 * pre-computed base price for each route (embedded by `build_synthetic_routes.py`).
 *
 * @returns Resolved {@link GameData} containing the full list of ICAO codes,
 *   all routes, and the price map keyed by sorted `"ORIG-DEST"` ICAO pair.
 */
export async function buildGameData(): Promise<GameData> {
  const rawGraph = await fetch(asset('data/route_graph.json')).then(r => r.json()) as AirportGraph

  const icaoCodes = Object.keys(rawGraph)
  const routes: Route[] = []
  const prices = new Map<string, number>()

  for (const [origin, destinations] of Object.entries(rawGraph)) {
    for (const [destination, edge] of Object.entries(destinations)) {
      routes.push({ origin, destination, frequency: edge.f, distance: edge.d, duration: edge.t })
      const key = origin < destination ? `${origin}-${destination}` : `${destination}-${origin}`
      if (!prices.has(key)) prices.set(key, edge.p)
    }
  }

  return { icaoCodes, routes, prices }
}