type GraphEdge = { f: number; d: number; t?: number }
type AirportGraph = Record<string, Record<string, GraphEdge>>

/** A route between two airports in the route network. */
export interface Route {
  /** ICAO code of the origin airport. */
  origin: string
  /** ICAO code of the destination airport. */
  destination: string
  /** Number of flights per day along this route. */
  frequency: number
  /** Great-circle distance in kilometres. */
  distance: number
  /** Average flight time in minutes, if known. */
  duration?: number
}

/**
 * The set of airports and routes that make up a single game instance,
 * generated by selecting a connected subgraph of the route network.
 */
export interface GameData {
  icaoCodes: string[]
  routes: Route[]
}

/**
 * Fetches the route graph, picks a random seed airport, then greedily expands
 * by adding the highest-frequency unvisited neighbor until `count` airports
 * are selected. Returns selected ICAO codes and all routes between them.
 */
export async function buildGameData(count = 50, minFreq = 1): Promise<GameData> {
  const rawGraph: AirportGraph = await fetch('/data/route_graph.json').then(r => r.json())

  const graph = new Map<string, Map<string, GraphEdge>>()
  for (const [orig, dests] of Object.entries(rawGraph)) {
    for (const [dest, edge] of Object.entries(dests)) {
      if (edge.f < minFreq) continue
      if (!graph.has(orig)) graph.set(orig, new Map())
      graph.get(orig)!.set(dest, edge)
    }
  }

  const nodes = [...graph.keys()]
  const seed = nodes[Math.floor(Math.random() * nodes.length)]

  const selected = new Set<string>([seed])
  const frontier = new Map<string, number>()

  const expand = (icao: string) => {
    for (const [dest, edge] of graph.get(icao) ?? []) {
      if (!selected.has(dest))
        frontier.set(dest, Math.max(frontier.get(dest) ?? 0, edge.f))
    }
  }

  expand(seed)

  while (selected.size < count && frontier.size > 0) {
    let best = '', bestFreq = -1
    for (const [icao, freq] of frontier)
      if (freq > bestFreq) { best = icao; bestFreq = freq }
    selected.add(best)
    frontier.delete(best)
    expand(best)
  }

  const routes: Route[] = []
  for (const [origin, destinations] of graph) {
    if (!selected.has(origin)) continue
    for (const [dest, edge] of destinations) {
      if (selected.has(dest)) routes.push({
        origin: origin,
        destination: dest,
        frequency: edge.f,
        distance: edge.d,
        duration: edge.t
      })
    }
  }

  return { icaoCodes: [...selected], routes }
}
